# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://healthhackconf.github.io
title: ヘルスハックカンファレンス
email: contact+hhc@zensow.jp
author: ヘルスハックカンファレンス実行委員
description: よい仕事をするため、いきいきとした人生を送るためには、自ら健康の重要性に目を向け、専門家に依存するのではなく、自らが日常的に実践しなければならない時代です。本カンファレンスは、ヘルスハックの実践を共有し、身体を動かし、美味しい食事を味わい、緑や潮風を感じる、全身で健康を楽しみながらヘルスハッカーに生まれ変わるためのイベントです。
copyright: 'Copyright &copy; 2016 ヘルスハックカンファレンス実行委員会. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Twitter
    icon: twitter
    url: https://twitter.com/healthhackconf
  - title: Facebook
    icon: facebook
    url: http://www.facebook.com/healthhackconf
  - title: Instagram
    icon: instagram
    url: http://www.instagram.com/healthhackconf
