# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://healthackconf.github.io
title: ヘルスハックカンファレンス
email: kakeda@zensow.jp
author: ヘルスハックカンファレンス実行委員
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 Healthy Hack Conference. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: コミュニティに参加
#    icon: home
#    url: https://goo.gl/tGI3CZ
